version: '3.6'

services: 
  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment: 
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: Ubistart
          # MYSQL_USER: user
          # MYSQL_PASSWORD: user
      ports:
      # <Port exposed> : < MySQL Port running inside container>
          - '3306:3306'
      volumes: 
          - ./init:/docker-entrypoint-initdb.d

  # adminer:
  #     image: adminer
  #     restart: always
  #     ports: 
  #         - 3:8080